name: DDM2
channels:
  - conda-forge
  - pytorch
  - dglteam
dependencies:
  - python=3.9
  - pip
  - matplotlib
  - jupyter
  - jupyterlab
  - pytorch
  - torchvision
  - torchtext
  - opencv
  - librosa
  - nb_conda_kernels
  - dgl>=0.4.3
  - beautifulsoup4
  - seaborn
  - pip:
    - nibabel
